version: '3.3'

services:
  powerflow:
    env_file: ../conf.env
    build:
      context: '.'
      dockerfile: './Dockerfile'
    networks: 
      - edgeflex-network
    volumes:
      - .:/powerflow
      - ../conf.json:/powerflow/examples/conf.json
      - ../cases:/powerflow/cases
    command: python3 runPF_new.py --ext_port 7070
    # command: tail -F dfsdfödslk
    ports:
      - 7070:8000
      - 1885:1883
    

networks:
  edgeflex-network:
    external:
      name: edgeflex-network